// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const isStudio = process.argv.some((arg) => arg.includes('studio'));

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: isStudio ? process.env.POSTGRES_DATABASE_URL : process.env.DATABASE_URL,
  },
});
